/**
 * Tool Registry — central catalog of all tools in the ToolPilot.
 * Each entry defines metadata used for search, navigation, and rendering.
 */

export const CATEGORIES = [
  'image',
  'document',
  'text',
  'developer',
  'media',
  'finance',
  'ai',
  'student',
  'design',
  'security',
  'seo',
  'utility',
  'spreadsheet',
];

const tools = [
  // ── Image ──────────────────────────────────────────────────────────
  {
    id: 'image-convert',
    name: 'Image Format Converter',
    description: 'Convert images between PNG, JPG, WEBP, SVG, GIF, BMP, TIFF, ICO, and AVIF',
    category: 'image',
    keywords: ['convert', 'png', 'jpg', 'webp', 'svg', 'gif', 'bmp', 'tiff', 'ico', 'avif', 'format', 'image'],
    path: '/tools/image/convert',
    icon: '🔀',
    isClientSide: false,
    supportedFormats: ['png', 'jpg', 'jpeg', 'webp', 'svg', 'gif', 'bmp', 'tiff', 'ico', 'avif'],
  },
  {
    id: 'image-compress',
    name: 'Image Compressor',
    description: 'Compress images to reduce file size with lossy or lossless modes',
    category: 'image',
    keywords: ['compress', 'optimize', 'reduce', 'size', 'quality', 'lossy', 'lossless', 'image'],
    path: '/tools/image/compress',
    icon: '🗜️',
    isClientSide: false,
  },
  {
    id: 'image-resize',
    name: 'Image Resizer',
    description: 'Resize images by pixel dimensions, percentage, or social media presets',
    category: 'image',
    keywords: ['resize', 'scale', 'dimensions', 'thumbnail', 'instagram', 'twitter', 'facebook', 'image'],
    path: '/tools/image/resize',
    icon: '↔️',
    isClientSide: false,
  },
  {
    id: 'image-edit',
    name: 'Image Editor',
    description: 'Crop, rotate, flip, and watermark images with real-time preview',
    category: 'image',
    keywords: ['crop', 'rotate', 'flip', 'watermark', 'edit', 'image'],
    path: '/tools/image/edit',
    icon: '🖌️',
    isClientSide: false,
  },
  {
    id: 'image-bg-remove',
    name: 'Background Remover',
    description: 'Remove image backgrounds with AI-powered detection and manual refinement',
    category: 'image',
    keywords: ['background', 'remove', 'transparent', 'cutout', 'ai', 'image'],
    path: '/tools/image/background-remove',
    icon: '✨',
    isClientSide: false,
  },

  // ── PDF ────────────────────────────────────────────────────────────
  {
    id: 'pdf-convert',
    name: 'PDF Converter',
    description: 'Convert images and documents to PDF, or PDF to PNG, JPG, and text',
    category: 'document',
    keywords: ['pdf', 'convert', 'png', 'jpg', 'text', 'document'],
    path: '/tools/pdf/convert',
    icon: '📄',
    isClientSide: false,
    supportedFormats: ['pdf', 'png', 'jpg', 'txt'],
  },
  {
    id: 'pdf-merge',
    name: 'PDF Merger',
    description: 'Merge multiple PDF files into a single document with drag-and-drop ordering',
    category: 'document',
    keywords: ['pdf', 'merge', 'combine', 'join', 'document'],
    path: '/tools/pdf/merge',
    icon: '🔗',
    isClientSide: false,
  },
  {
    id: 'pdf-split',
    name: 'PDF Splitter',
    description: 'Split a PDF into separate files by page ranges',
    category: 'document',
    keywords: ['pdf', 'split', 'separate', 'extract', 'pages', 'document'],
    path: '/tools/pdf/split',
    icon: '✂️',
    isClientSide: false,
  },
  {
    id: 'pdf-compress',
    name: 'PDF Compressor',
    description: 'Compress PDF files to reduce size while maintaining quality',
    category: 'document',
    keywords: ['pdf', 'compress', 'reduce', 'size', 'optimize', 'document'],
    path: '/tools/pdf/compress',
    icon: '📉',
    isClientSide: false,
  },
  {
    id: 'pdf-protect',
    name: 'PDF Password Protect',
    description: 'Add or remove password protection on PDF documents',
    category: 'document',
    keywords: ['pdf', 'password', 'protect', 'encrypt', 'unlock', 'security', 'document'],
    path: '/tools/pdf/protect',
    icon: '🔐',
    isClientSide: false,
  },
  {
    id: 'pdf-reorder',
    name: 'PDF Page Reorder',
    description: 'Reorder PDF pages with drag-and-drop thumbnails',
    category: 'document',
    keywords: ['pdf', 'reorder', 'rearrange', 'pages', 'sort', 'document'],
    path: '/tools/pdf/reorder',
    icon: '🔃',
    isClientSide: false,
  },
  {
    id: 'pdf-rotate',
    name: 'PDF Page Rotate',
    description: 'Rotate selected PDF pages by 90, 180, or 270 degrees',
    category: 'document',
    keywords: ['pdf', 'rotate', 'orientation', 'pages', 'document'],
    path: '/tools/pdf/rotate',
    icon: '🔄',
    isClientSide: false,
  },
  {
    id: 'pdf-watermark',
    name: 'PDF Watermark',
    description: 'Add text or image watermarks to PDF pages with configurable opacity and position',
    category: 'document',
    keywords: ['pdf', 'watermark', 'stamp', 'overlay', 'document'],
    path: '/tools/pdf/watermark',
    icon: '💦',
    isClientSide: false,
  },
  {
    id: 'pdf-pages',
    name: 'PDF Page Manager',
    description: 'Add, delete, or extract individual pages from a PDF',
    category: 'document',
    keywords: ['pdf', 'pages', 'add', 'delete', 'extract', 'manage', 'document'],
    path: '/tools/pdf/pages',
    icon: '📑',
    isClientSide: false,
  },
  {
    id: 'pdf-esignature',
    name: 'E-Signature',
    description: 'Draw, type, or upload a signature and place it on PDF documents',
    category: 'document',
    keywords: ['signature', 'sign', 'pdf', 'esign', 'document', 'draw'],
    path: '/tools/pdf/esignature',
    icon: '✒️',
    isClientSide: false,
  },

  // ── Document ───────────────────────────────────────────────────────
  {
    id: 'document-convert',
    name: 'Document Converter',
    description: 'Convert between Markdown, HTML, plain text, CSV, and XLSX formats',
    category: 'document',
    keywords: ['document', 'convert', 'markdown', 'html', 'csv', 'xlsx', 'text'],
    path: '/tools/document/convert',
    icon: '📝',
    isClientSide: false,
    supportedFormats: ['md', 'html', 'txt', 'csv', 'xlsx'],
  },

  // ── Text ────────────────────────────────────────────────────────────
  {
    id: 'text-utilities',
    name: 'Text Utilities',
    description: 'Case conversion, word count, encoding, hashing, diff, lorem ipsum, and find-replace',
    category: 'text',
    keywords: ['text', 'case', 'uppercase', 'lowercase', 'word count', 'base64', 'hash', 'diff', 'lorem', 'find', 'replace'],
    path: '/tools/text/utilities',
    icon: '🔡',
    isClientSide: true,
  },
  {
    id: 'markdown-editor',
    name: 'Markdown Editor',
    description: 'Write Markdown with live preview, formatting toolbar, and HTML/PDF export',
    category: 'text',
    keywords: ['markdown', 'editor', 'preview', 'html', 'pdf', 'write', 'format'],
    path: '/tools/text/markdown-editor',
    icon: '📓',
    isClientSide: true,
  },
  {
    id: 'text-summarizer',
    name: 'Text Summarizer',
    description: 'Summarize long text into concise summaries with adjustable length',
    category: 'text',
    keywords: ['summarize', 'summary', 'extract', 'condense', 'text', 'article'],
    path: '/tools/text/summarizer',
    icon: '📊',
    isClientSide: true,
  },
  {
    id: 'ocr',
    name: 'OCR — Image to Text',
    description: 'Extract text from images and scanned documents in 10+ languages',
    category: 'text',
    keywords: ['ocr', 'extract', 'text', 'image', 'scan', 'recognize'],
    path: '/tools/text/ocr',
    icon: '🔍',
    isClientSide: false,
  },

  // ── Developer ──────────────────────────────────────────────────────
  {
    id: 'json-yaml-xml',
    name: 'JSON / YAML / XML Formatter',
    description: 'Format, validate, and convert between JSON, YAML, and XML',
    category: 'developer',
    keywords: ['json', 'yaml', 'xml', 'format', 'validate', 'convert', 'syntax'],
    path: '/tools/developer/json-yaml-xml',
    icon: '🧩',
    isClientSide: true,
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode JWT tokens and inspect header, payload, signature, and expiration',
    category: 'developer',
    keywords: ['jwt', 'token', 'decode', 'header', 'payload', 'auth'],
    path: '/tools/developer/jwt-decoder',
    icon: '🗝️',
    isClientSide: true,
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions with real-time matching and group highlighting',
    category: 'developer',
    keywords: ['regex', 'regular expression', 'pattern', 'match', 'test'],
    path: '/tools/developer/regex-tester',
    icon: '🎯',
    isClientSide: true,
  },
  {
    id: 'cron-parser',
    name: 'Cron Expression Parser',
    description: 'Parse cron expressions and display the next 5 scheduled execution times',
    category: 'developer',
    keywords: ['cron', 'schedule', 'expression', 'parse', 'time'],
    path: '/tools/developer/cron-parser',
    icon: '⏲️',
    isClientSide: true,
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable date-time formats',
    category: 'developer',
    keywords: ['timestamp', 'unix', 'epoch', 'date', 'time', 'convert'],
    path: '/tools/developer/timestamp-converter',
    icon: '🕰️',
    isClientSide: true,
  },
  {
    id: 'css-minify',
    name: 'CSS Minifier / Beautifier',
    description: 'Minify or beautify CSS code for production or readability',
    category: 'developer',
    keywords: ['css', 'minify', 'beautify', 'format', 'compress', 'style'],
    path: '/tools/developer/css-minify',
    icon: '💅',
    isClientSide: true,
  },
  {
    id: 'html-minify',
    name: 'HTML Minifier / Beautifier',
    description: 'Minify or beautify HTML markup for production or readability',
    category: 'developer',
    keywords: ['html', 'minify', 'beautify', 'format', 'compress', 'markup'],
    path: '/tools/developer/html-minify',
    icon: '🏗️',
    isClientSide: true,
  },
  {
    id: 'data-transformer',
    name: 'Data Transformer',
    description: 'Convert between JSON, CSV, YAML, and XML data formats',
    category: 'developer',
    keywords: ['data', 'transform', 'json', 'csv', 'yaml', 'xml', 'convert'],
    path: '/tools/developer/data-transformer',
    icon: '🔀',
    isClientSide: true,
  },

  // ── Media ───────────────────────────────────────────────────────────
  {
    id: 'audio-convert',
    name: 'Audio Converter',
    description: 'Convert audio between MP3, WAV, OGG, FLAC, AAC, and M4A with bitrate control',
    category: 'media',
    keywords: ['audio', 'convert', 'mp3', 'wav', 'ogg', 'flac', 'aac', 'm4a', 'sound'],
    path: '/tools/media/audio-convert',
    icon: '🎵',
    isClientSide: false,
    supportedFormats: ['mp3', 'wav', 'ogg', 'flac', 'aac', 'm4a'],
  },
  {
    id: 'video-convert',
    name: 'Video Converter',
    description: 'Convert video between MP4, WEBM, AVI, MOV, and MKV with resolution control',
    category: 'media',
    keywords: ['video', 'convert', 'mp4', 'webm', 'avi', 'mov', 'mkv'],
    path: '/tools/media/video-convert',
    icon: '🎥',
    isClientSide: false,
    supportedFormats: ['mp4', 'webm', 'avi', 'mov', 'mkv'],
  },
  {
    id: 'gif-maker',
    name: 'GIF Maker',
    description: 'Create animated GIFs from images or video clips with frame control',
    category: 'media',
    keywords: ['gif', 'animation', 'create', 'images', 'video', 'frames'],
    path: '/tools/media/gif-maker',
    icon: '🎞️',
    isClientSide: false,
  },

  // ── AI ──────────────────────────────────────────────────────────────
  {
    id: 'ai-detector',
    name: 'AI Content Detector',
    description: 'Analyze text and images to detect AI-generated content with confidence scores',
    category: 'ai',
    keywords: ['ai', 'detect', 'artificial intelligence', 'generated', 'content', 'text', 'image'],
    path: '/tools/ai/ai-detector',
    icon: '🧠',
    isClientSide: true,
  },

  // ── Student ─────────────────────────────────────────────────────────
  {
    id: 'citation-generator',
    name: 'Citation Generator',
    description: 'Generate APA, MLA, Chicago, Harvard, IEEE, and Vancouver citations with DOI/ISBN lookup and bibliography management',
    category: 'student',
    keywords: ['citation', 'bibliography', 'apa', 'mla', 'chicago', 'harvard', 'ieee', 'vancouver', 'reference', 'academic', 'doi', 'isbn'],
    path: '/tools/student/citation-generator',
    icon: '📖',
    isClientSide: true,
  },
  {
    id: 'academic-metrics',
    name: 'Academic Text Metrics',
    description: 'Word count, page estimates, speaking time, and readability scores for academic text',
    category: 'student',
    keywords: ['academic', 'metrics', 'readability', 'word count', 'pages', 'speaking time', 'flesch'],
    path: '/tools/student/academic-metrics',
    icon: '📏',
    isClientSide: true,
  },
  {
    id: 'gpa-calculator',
    name: 'GPA Calculator',
    description: 'Calculate semester and cumulative GPA with custom grading scales',
    category: 'student',
    keywords: ['gpa', 'grade', 'calculator', 'semester', 'cumulative', 'academic'],
    path: '/tools/student/gpa-calculator',
    icon: '🧮',
    isClientSide: true,
  },
  {
    id: 'latex-renderer',
    name: 'LaTeX Math Renderer',
    description: 'Render LaTeX math expressions with live preview and PNG/SVG export',
    category: 'student',
    keywords: ['latex', 'math', 'equation', 'render', 'formula', 'katex'],
    path: '/tools/student/latex-renderer',
    icon: '∫',
    isClientSide: true,
  },
  {
    id: 'study-timer',
    name: 'Pomodoro Study Timer',
    description: 'Pomodoro and custom study timer with session tracking and history',
    category: 'student',
    keywords: ['pomodoro', 'timer', 'study', 'focus', 'break', 'session'],
    path: '/tools/student/study-timer',
    icon: '⏱️',
    isClientSide: true,
  },
  {
    id: 'flashcards',
    name: 'Flashcard Generator',
    description: 'Create, study, and export flashcards with flip animation and CSV import',
    category: 'student',
    keywords: ['flashcard', 'study', 'quiz', 'review', 'cards', 'csv'],
    path: '/tools/student/flashcards',
    icon: '🗂️',
    isClientSide: true,
  },
  {
    id: 'scientific-calculator',
    name: 'Scientific Calculator',
    description: 'Advanced calculator with trig, log, factorial, constants, and calculation history',
    category: 'student',
    keywords: ['calculator', 'scientific', 'math', 'trig', 'sin', 'cos', 'log', 'factorial'],
    path: '/tools/student/scientific-calculator',
    icon: '🔢',
    isClientSide: true,
  },
  {
    id: 'essay-outline',
    name: 'Essay Outline Generator',
    description: 'Generate structured essay outlines for argumentative, expository, and other essay types',
    category: 'student',
    keywords: ['essay', 'outline', 'writing', 'structure', 'thesis', 'academic'],
    path: '/tools/student/essay-outline',
    icon: '📋',
    isClientSide: true,
  },
  {
    id: 'graphing-calculator',
    name: 'Graphing Calculator',
    description: 'Plot mathematical functions with interactive 2D graphing, zoom, pan, and multiple equations',
    category: 'student',
    keywords: ['graph', 'plot', 'function', 'math', 'calculator', 'equation', 'desmos', '2d', 'curve'],
    path: '/tools/student/graphing-calculator',
    icon: '📈',
    isClientSide: true,
  },
  { id: 'math-solver', name: 'Step-by-Step Math Solver', description: 'Solve linear equations, quadratics, derivatives, and integrals with detailed step-by-step explanations', category: 'student', keywords: ['math', 'solver', 'equation', 'step by step', 'algebra', 'calculus', 'derivative', 'integral', 'quadratic'], path: '/tools/student/math-solver', icon: '🧮', isClientSide: true },

  // ── Design ──────────────────────────────────────────────────────────
  {
    id: 'color-tools',
    name: 'Color Tools',
    description: 'Color conversion, palette generation, contrast checker, and image palette extraction',
    category: 'design',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'palette', 'contrast', 'picker', 'wcag'],
    path: '/tools/design/color-tools',
    icon: '🎨',
    isClientSide: true,
  },
  {
    id: 'meme-generator',
    name: 'Meme Generator',
    description: 'Create memes from 100+ popular Imgflip templates with custom text, fonts, and export options',
    category: 'design',
    keywords: ['meme', 'template', 'social media', 'graphic', 'text', 'image', 'imgflip', 'funny', 'caption'],
    path: '/tools/design/meme-generator',
    icon: '🖼️',
    isClientSide: true,
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    description: 'Generate a complete favicon set from a single image for web projects',
    category: 'design',
    keywords: ['favicon', 'icon', 'web', 'ico', 'png', 'apple touch', 'pwa'],
    path: '/tools/design/favicon-generator',
    icon: '⭐',
    isClientSide: false,
  },

  // ── Security ────────────────────────────────────────────────────────
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure random passwords and passphrases with strength indicator',
    category: 'security',
    keywords: ['password', 'generate', 'secure', 'random', 'passphrase', 'strength'],
    path: '/tools/security/password-generator',
    icon: '🔐',
    isClientSide: true,
  },
  {
    id: 'checksum-calculator',
    name: 'Checksum Calculator',
    description: 'Compute MD5, SHA-1, and SHA-256 file checksums client-side for integrity verification',
    category: 'security',
    keywords: ['checksum', 'hash', 'md5', 'sha', 'integrity', 'verify', 'file'],
    path: '/tools/security/checksum-calculator',
    icon: '🛡️',
    isClientSide: true,
  },

  // ── SEO ─────────────────────────────────────────────────────────────
  {
    id: 'seo-analyzer',
    name: 'SEO Analyzer',
    description: 'Analyze web pages for SEO quality with scores and improvement suggestions',
    category: 'seo',
    keywords: ['seo', 'meta', 'tags', 'analyze', 'keywords', 'open graph', 'twitter card'],
    path: '/tools/seo/seo-analyzer',
    icon: '📈',
    isClientSide: false,
  },

  // ── Utility ─────────────────────────────────────────────────────────
  {
    id: 'unit-converter',
    name: 'Unit & Currency Converter',
    description: 'Convert between units of length, weight, volume, temperature, currency, and time zones',
    category: 'utility',
    keywords: ['unit', 'convert', 'length', 'weight', 'temperature', 'currency', 'timezone'],
    path: '/tools/utility/unit-converter',
    icon: '⚖️',
    isClientSide: true,
  },
  {
    id: 'qr-barcode',
    name: 'QR Code & Barcode Generator',
    description: 'Generate and scan QR codes and barcodes with customizable colors and formats',
    category: 'utility',
    keywords: ['qr', 'barcode', 'generate', 'scan', 'code', 'encode', 'decode'],
    path: '/tools/utility/qr-barcode',
    icon: '📲',
    isClientSide: false,
  },

  // ── Spreadsheet (NEW) ──────────────────────────────────────────────
  { id: 'excel-to-csv', name: 'Excel to CSV', description: 'Convert Excel spreadsheets (.xlsx, .xls) to CSV format', category: 'spreadsheet', keywords: ['excel', 'csv', 'xlsx', 'xls', 'convert', 'spreadsheet'], path: '/tools/spreadsheet/excel-to-csv', icon: '📊', isClientSide: true },
  { id: 'csv-to-excel', name: 'CSV to Excel', description: 'Convert CSV files to Excel spreadsheet format (.xlsx)', category: 'spreadsheet', keywords: ['csv', 'excel', 'xlsx', 'convert', 'spreadsheet'], path: '/tools/spreadsheet/csv-to-excel', icon: '📗', isClientSide: true },
  { id: 'excel-to-json', name: 'Excel to JSON', description: 'Convert Excel spreadsheets to JSON with automatic column mapping', category: 'spreadsheet', keywords: ['excel', 'json', 'xlsx', 'convert', 'data'], path: '/tools/spreadsheet/excel-to-json', icon: '🔄', isClientSide: true },
  { id: 'json-to-excel', name: 'JSON to Excel', description: 'Convert JSON data to downloadable Excel spreadsheets', category: 'spreadsheet', keywords: ['json', 'excel', 'xlsx', 'convert', 'data'], path: '/tools/spreadsheet/json-to-excel', icon: '📥', isClientSide: true },
  { id: 'csv-viewer', name: 'CSV Viewer & Editor', description: 'View, edit, sort, and filter CSV files with a spreadsheet-like interface', category: 'spreadsheet', keywords: ['csv', 'viewer', 'editor', 'sort', 'filter', 'spreadsheet', 'table'], path: '/tools/spreadsheet/csv-viewer', icon: '👁️', isClientSide: true },
  { id: 'merge-csv', name: 'Merge CSV Files', description: 'Combine multiple CSV files into one with column matching', category: 'spreadsheet', keywords: ['csv', 'merge', 'combine', 'join', 'concatenate', 'spreadsheet'], path: '/tools/spreadsheet/merge-csv', icon: '🔗', isClientSide: true },
  { id: 'csv-deduplicate', name: 'Remove Duplicates', description: 'Find and remove duplicate rows from CSV and Excel files', category: 'spreadsheet', keywords: ['csv', 'excel', 'duplicates', 'remove', 'deduplicate', 'clean'], path: '/tools/spreadsheet/deduplicate', icon: '🧹', isClientSide: true },
  { id: 'csv-to-sql', name: 'CSV to SQL', description: 'Generate SQL INSERT statements or CREATE TABLE from CSV data', category: 'spreadsheet', keywords: ['csv', 'sql', 'insert', 'create table', 'database', 'convert'], path: '/tools/spreadsheet/csv-to-sql', icon: '🗃️', isClientSide: true },
  { id: 'pivot-table', name: 'Pivot Table Generator', description: 'Create pivot tables from CSV data with grouping, cross-tabulation, and aggregation functions', category: 'spreadsheet', keywords: ['pivot', 'table', 'csv', 'group', 'aggregate', 'sum', 'count', 'average', 'cross tab'], path: '/tools/spreadsheet/pivot-table', icon: '📊', isClientSide: true },
  { id: 'json-flattener', name: 'JSON Flattener', description: 'Flatten nested JSON objects to flat key-value pairs for CSV conversion', category: 'spreadsheet', keywords: ['json', 'flatten', 'nested', 'csv', 'convert', 'key value', 'dot notation'], path: '/tools/spreadsheet/json-flattener', icon: '📋', isClientSide: true },

  // ── Document (Phase 3 differentiators) ──────────────────────────────
  { id: 'pdf-ocr', name: 'PDF OCR', description: 'Extract text from scanned PDFs using OCR with multi-language support', category: 'document', keywords: ['pdf', 'ocr', 'scan', 'text', 'extract', 'tesseract', 'scanned'], path: '/tools/pdf/ocr', icon: '🔍', isClientSide: false },
  { id: 'pdf-flatten', name: 'PDF Flatten', description: 'Remove form fields and interactive elements from PDFs to create static documents', category: 'document', keywords: ['pdf', 'flatten', 'form', 'fields', 'static', 'interactive', 'remove'], path: '/tools/pdf/flatten', icon: '📋', isClientSide: false },
  { id: 'html-to-pdf', name: 'HTML to PDF', description: 'Convert HTML content to PDF with live preview and browser-native rendering', category: 'document', keywords: ['html', 'pdf', 'convert', 'web', 'page', 'print', 'css'], path: '/tools/document/html-to-pdf', icon: '🌐', isClientSide: true },
  { id: 'pdf-form-filler', name: 'PDF Form Filler', description: 'Detect and fill interactive form fields in PDFs — text, checkboxes, dropdowns, and radio buttons', category: 'document', keywords: ['pdf', 'form', 'fill', 'fields', 'interactive', 'text', 'checkbox', 'dropdown'], path: '/tools/pdf/form-filler', icon: '📝', isClientSide: true },
  { id: 'pdf-compare', name: 'PDF Comparison', description: 'Compare two PDFs side-by-side with text diff highlighting and visual page comparison', category: 'document', keywords: ['pdf', 'compare', 'diff', 'difference', 'side by side', 'visual', 'text'], path: '/tools/pdf/compare', icon: '🔍', isClientSide: true },
  { id: 'pdf-page-numbers', name: 'Add Page Numbers', description: 'Add customizable page numbers to your PDF — choose position, format, font size, and color', category: 'document', keywords: ['pdf', 'page', 'numbers', 'numbering', 'footer', 'header', 'count'], path: '/tools/pdf/page-numbers', icon: '#️⃣', isClientSide: true },
  { id: 'pdf-unlock', name: 'Unlock PDF', description: 'Remove password protection from encrypted PDFs — 100% in your browser', category: 'document', keywords: ['pdf', 'unlock', 'password', 'remove', 'decrypt', 'protection', 'encrypted'], path: '/tools/pdf/unlock', icon: '🔓', isClientSide: true },
  { id: 'pdf-crop', name: 'Crop PDF', description: 'Crop PDF pages by setting margins — visual preview with apply to all or specific pages', category: 'document', keywords: ['pdf', 'crop', 'trim', 'margins', 'resize', 'cut', 'border'], path: '/tools/pdf/crop', icon: '✂️', isClientSide: true },
  { id: 'pdf-redact', name: 'Redact PDF', description: 'Permanently black out sensitive content in PDFs — redacted areas cannot be recovered', category: 'document', keywords: ['pdf', 'redact', 'black', 'out', 'censor', 'sensitive', 'privacy', 'hide'], path: '/tools/pdf/redact', icon: '█', isClientSide: true },

  // ── Document (additions) ───────────────────────────────────────────
  { id: 'word-to-pdf', name: 'Word to PDF', description: 'Convert Word documents (.docx) to PDF format', category: 'document', keywords: ['word', 'docx', 'pdf', 'convert', 'document', 'microsoft'], path: '/tools/document/word-to-pdf', icon: '📄', isClientSide: false },
  { id: 'pdf-to-word', name: 'PDF to Word', description: 'Convert PDF files to editable Word documents (.docx)', category: 'document', keywords: ['pdf', 'word', 'docx', 'convert', 'document', 'editable'], path: '/tools/document/pdf-to-word', icon: '📝', isClientSide: false },
  { id: 'pdf-to-excel', name: 'PDF to Excel', description: 'Extract tables from PDF files into Excel spreadsheets', category: 'document', keywords: ['pdf', 'excel', 'xlsx', 'table', 'extract', 'convert'], path: '/tools/document/pdf-to-excel', icon: '📊', isClientSide: false },
  { id: 'ppt-to-pdf', name: 'PowerPoint to PDF', description: 'Convert PowerPoint presentations to PDF format', category: 'document', keywords: ['powerpoint', 'ppt', 'pptx', 'pdf', 'convert', 'presentation', 'slides'], path: '/tools/document/ppt-to-pdf', icon: '📽️', isClientSide: false },

  // ── Text (additions) ───────────────────────────────────────────────
  { id: 'plagiarism-checker', name: 'Plagiarism Checker', description: 'Check text for potential plagiarism with similarity detection', category: 'text', keywords: ['plagiarism', 'check', 'duplicate', 'similarity', 'copy', 'original'], path: '/tools/text/plagiarism-checker', icon: '🔎', isClientSide: true },
  { id: 'grammar-checker', name: 'Grammar Checker', description: 'Check and fix grammar, spelling, and punctuation errors', category: 'text', keywords: ['grammar', 'spell', 'check', 'punctuation', 'writing', 'proofread'], path: '/tools/text/grammar-checker', icon: '✅', isClientSide: true },
  { id: 'paraphraser', name: 'Paraphrasing Tool', description: 'Rewrite text in different words while keeping the meaning', category: 'text', keywords: ['paraphrase', 'rewrite', 'rephrase', 'synonym', 'text'], path: '/tools/text/paraphraser', icon: '🔁', isClientSide: true },
  { id: 'text-to-speech', name: 'Text to Speech', description: 'Convert text to natural-sounding audio with multiple voices', category: 'text', keywords: ['text', 'speech', 'audio', 'voice', 'tts', 'read aloud'], path: '/tools/text/text-to-speech', icon: '🔊', isClientSide: true },

  { id: 'writing-templates', name: 'Writing Templates', description: 'Pre-built templates for emails, blogs, resumes, cover letters, and more with fill-in-the-blank placeholders', category: 'text', keywords: ['template', 'writing', 'email', 'blog', 'resume', 'cover letter', 'business', 'academic'], path: '/tools/text/writing-templates', icon: '📝', isClientSide: true },

  // ── Utility (additions) ────────────────────────────────────────────
  { id: 'age-calculator', name: 'Age Calculator', description: 'Calculate exact age in years, months, and days from date of birth', category: 'utility', keywords: ['age', 'calculator', 'birthday', 'date', 'years', 'months'], path: '/tools/utility/age-calculator', icon: '🎂', isClientSide: true },
  { id: 'date-calculator', name: 'Date Difference Calculator', description: 'Calculate the number of days, weeks, and months between two dates', category: 'utility', keywords: ['date', 'difference', 'calculator', 'days', 'between', 'duration'], path: '/tools/utility/date-calculator', icon: '📅', isClientSide: true },
  { id: 'percentage-calculator', name: 'Percentage Calculator', description: 'Calculate percentages, percentage change, and percentage of a number', category: 'utility', keywords: ['percentage', 'calculator', 'percent', 'change', 'increase', 'decrease'], path: '/tools/utility/percentage-calculator', icon: '💯', isClientSide: true },
  { id: 'loan-calculator', name: 'Loan & EMI Calculator', description: 'Calculate monthly EMI, total interest, and amortization schedule', category: 'utility', keywords: ['loan', 'emi', 'calculator', 'interest', 'mortgage', 'amortization'], path: '/tools/utility/loan-calculator', icon: '🏦', isClientSide: true },
  { id: 'bmi-calculator', name: 'BMI Calculator', description: 'Calculate Body Mass Index with health category classification', category: 'utility', keywords: ['bmi', 'body mass', 'calculator', 'health', 'weight', 'height'], path: '/tools/utility/bmi-calculator', icon: '⚕️', isClientSide: true },
  { id: 'number-to-words', name: 'Number to Words', description: 'Convert numbers to written words in multiple languages', category: 'utility', keywords: ['number', 'words', 'convert', 'text', 'spell', 'write'], path: '/tools/utility/number-to-words', icon: '🔢', isClientSide: true },
  { id: 'ip-lookup', name: 'IP Address Lookup', description: 'Look up IP address geolocation, ISP, and network details', category: 'utility', keywords: ['ip', 'address', 'lookup', 'geolocation', 'isp', 'network', 'whois'], path: '/tools/utility/ip-lookup', icon: '🌍', isClientSide: false },
  { id: 'url-shortener', name: 'URL Shortener', description: 'Shorten long URLs into compact, shareable links', category: 'utility', keywords: ['url', 'shorten', 'link', 'short', 'tiny', 'compact'], path: '/tools/utility/url-shortener', icon: '🔗', isClientSide: false },
  { id: 'world-clock', name: 'World Clock & Timezone Converter', description: 'View current time across cities, convert between timezones, and plan meetings across time zones', category: 'utility', keywords: ['world', 'clock', 'timezone', 'time', 'convert', 'meeting', 'planner', 'city'], path: '/tools/utility/world-clock', icon: '🌍', isClientSide: true },
  { id: 'countdown-timer', name: 'Countdown Timer', description: 'Count down to any date with live updating display and preset events', category: 'utility', keywords: ['countdown', 'timer', 'date', 'event', 'days until', 'new year', 'christmas'], path: '/tools/utility/countdown-timer', icon: '⏳', isClientSide: true },

  // ── Developer (additions) ──────────────────────────────────────────
  { id: 'url-encoder', name: 'URL Encoder / Decoder', description: 'Encode or decode URLs and query parameters', category: 'developer', keywords: ['url', 'encode', 'decode', 'percent', 'query', 'parameter'], path: '/tools/developer/url-encoder', icon: '🔗', isClientSide: true },
  { id: 'base64-file', name: 'Base64 File Encoder', description: 'Encode files to Base64 or decode Base64 strings to files', category: 'developer', keywords: ['base64', 'encode', 'decode', 'file', 'binary', 'string'], path: '/tools/developer/base64-file', icon: '📦', isClientSide: true },
  { id: 'json-schema', name: 'JSON Schema Validator', description: 'Validate JSON data against a JSON Schema definition', category: 'developer', keywords: ['json', 'schema', 'validate', 'definition', 'structure'], path: '/tools/developer/json-schema', icon: '✅', isClientSide: true },
  { id: 'sql-formatter', name: 'SQL Formatter', description: 'Format and beautify SQL queries with syntax highlighting', category: 'developer', keywords: ['sql', 'format', 'beautify', 'query', 'database', 'syntax'], path: '/tools/developer/sql-formatter', icon: '🗄️', isClientSide: true },
  { id: 'diff-checker', name: 'Diff Checker', description: 'Compare two texts or files and highlight differences side by side', category: 'developer', keywords: ['diff', 'compare', 'difference', 'text', 'file', 'merge'], path: '/tools/developer/diff-checker', icon: '⚖️', isClientSide: true },
  { id: 'color-code-converter', name: 'Color Code Converter', description: 'Convert between HEX, RGB, HSL, and other color formats instantly', category: 'developer', keywords: ['color', 'hex', 'rgb', 'hsl', 'convert', 'code', 'css'], path: '/tools/developer/color-code-converter', icon: '🌈', isClientSide: true },

  // ── SEO (additions) ────────────────────────────────────────────────
  { id: 'heading-analyzer', name: 'Heading Structure Analyzer', description: 'Analyze H1-H6 heading hierarchy for SEO with issue detection and scoring', category: 'seo', keywords: ['heading', 'h1', 'h2', 'structure', 'hierarchy', 'seo', 'analyzer', 'html'], path: '/tools/seo/heading-analyzer', icon: '🏗️', isClientSide: true },
  { id: 'meta-tag-generator', name: 'Meta Tag Generator', description: 'Generate SEO-optimized meta tags, Open Graph, and Twitter Cards', category: 'seo', keywords: ['meta', 'tag', 'generator', 'og', 'twitter', 'seo', 'social'], path: '/tools/seo/meta-tag-generator', icon: '🏷️', isClientSide: true },
  { id: 'robots-txt-generator', name: 'Robots.txt Generator', description: 'Create and validate robots.txt files for search engine crawlers', category: 'seo', keywords: ['robots', 'txt', 'generator', 'crawler', 'search', 'seo'], path: '/tools/seo/robots-txt-generator', icon: '🤖', isClientSide: true },
  { id: 'sitemap-generator', name: 'Sitemap Generator', description: 'Generate XML sitemaps from a list of URLs for search engines', category: 'seo', keywords: ['sitemap', 'xml', 'generator', 'urls', 'search', 'seo'], path: '/tools/seo/sitemap-generator', icon: '🗺️', isClientSide: true },
  { id: 'keyword-density', name: 'Keyword Density Checker', description: 'Analyze keyword frequency and density in your content', category: 'seo', keywords: ['keyword', 'density', 'frequency', 'seo', 'content', 'analysis'], path: '/tools/seo/keyword-density', icon: '📊', isClientSide: true },
  { id: 'page-speed', name: 'Page Speed Insights', description: 'Analyze website performance with Core Web Vitals, LCP, CLS, and improvement suggestions', category: 'seo', keywords: ['page speed', 'performance', 'lighthouse', 'core web vitals', 'lcp', 'cls', 'fcp', 'seo'], path: '/tools/seo/page-speed', icon: '⚡', isClientSide: false },
  { id: 'redirect-checker', name: 'Redirect Chain Checker', description: 'Follow and visualize URL redirect chains with status codes and loop detection', category: 'seo', keywords: ['redirect', 'chain', '301', '302', 'url', 'seo', 'http'], path: '/tools/seo/redirect-checker', icon: '🔗', isClientSide: false },

  // ── Media (additions) ──────────────────────────────────────────────
  { id: 'video-to-gif', name: 'Video to GIF', description: 'Convert video clips to animated GIF with custom frame rate and size', category: 'media', keywords: ['video', 'gif', 'convert', 'animation', 'clip'], path: '/tools/media/video-to-gif', icon: '🎬', isClientSide: false },
  { id: 'audio-trimmer', name: 'Audio Trimmer', description: 'Trim and cut audio files with waveform visualization', category: 'media', keywords: ['audio', 'trim', 'cut', 'clip', 'waveform', 'mp3'], path: '/tools/media/audio-trimmer', icon: '✂️', isClientSide: false },
  { id: 'video-compressor', name: 'Video Compressor', description: 'Compress video files to reduce size while maintaining quality', category: 'media', keywords: ['video', 'compress', 'reduce', 'size', 'quality', 'mp4'], path: '/tools/media/video-compressor', icon: '📉', isClientSide: false },

  // ── Image (additions) ──────────────────────────────────────────────
  { id: 'image-to-pdf', name: 'Image to PDF', description: 'Convert one or multiple images into a single PDF document', category: 'image', keywords: ['image', 'pdf', 'convert', 'photo', 'picture', 'document'], path: '/tools/image/image-to-pdf', icon: '📄', isClientSide: false },
  { id: 'heic-to-jpg', name: 'HEIC to JPG', description: 'Convert iPhone HEIC/HEIF photos to JPG format', category: 'image', keywords: ['heic', 'heif', 'jpg', 'jpeg', 'convert', 'iphone', 'apple'], path: '/tools/image/heic-to-jpg', icon: '📱', isClientSide: false },
  { id: 'svg-to-png', name: 'SVG to PNG', description: 'Convert SVG vector graphics to PNG raster images at any resolution', category: 'image', keywords: ['svg', 'png', 'convert', 'vector', 'raster', 'resolution'], path: '/tools/image/svg-to-png', icon: '🖼️', isClientSide: false },

  // ── Security (additions) ───────────────────────────────────────────
  { id: 'hash-generator', name: 'Hash Generator', description: 'Generate MD5, SHA-1, SHA-256, and SHA-512 hashes from text', category: 'security', keywords: ['hash', 'md5', 'sha', 'sha256', 'sha512', 'generate', 'text'], path: '/tools/security/hash-generator', icon: '🔏', isClientSide: true },
  { id: 'uuid-generator', name: 'UUID Generator', description: 'Generate random UUIDs (v4) and ULIDs for development', category: 'security', keywords: ['uuid', 'ulid', 'generate', 'random', 'unique', 'id'], path: '/tools/security/uuid-generator', icon: '🆔', isClientSide: true },
  { id: 'file-encryption', name: 'File Encryption', description: 'Encrypt and decrypt files with AES-256 in your browser — nothing leaves your device', category: 'security', keywords: ['encrypt', 'decrypt', 'file', 'aes', 'password', 'security', 'privacy', 'cipher'], path: '/tools/security/file-encryption', icon: '🔒', isClientSide: true },
  { id: 'totp-generator', name: 'TOTP Generator', description: 'Generate time-based one-time passwords for testing 2FA with QR code export', category: 'security', keywords: ['totp', '2fa', 'authenticator', 'otp', 'two factor', 'qr', 'secret', 'security'], path: '/tools/security/totp-generator', icon: '🔑', isClientSide: true },
  { id: 'breach-checker', name: 'Breach Checker', description: 'Check if your email or password has been exposed in known data breaches', category: 'security', keywords: ['breach', 'pwned', 'email', 'password', 'hack', 'leak', 'security', 'hibp'], path: '/tools/security/breach-checker', icon: '🔍', isClientSide: true },
  { id: 'secure-random', name: 'Secure Random Generator', description: 'Cryptographically secure random numbers, dice rolls, coin flips, card draws, and list shuffling', category: 'security', keywords: ['random', 'secure', 'dice', 'coin', 'flip', 'lottery', 'shuffle', 'crypto'], path: '/tools/security/secure-random', icon: '🎲', isClientSide: true },

  // ── Finance & Trading ──────────────────────────────────────────────
  { id: 'spy-spx-converter', name: 'ETF ↔ Index Converter', description: 'Convert between SPY/SPX and QQQ/NDX using the actual current ratio — not a hardcoded multiplier', category: 'finance', keywords: ['spy', 'spx', 'qqq', 'ndx', 'sp500', 'nasdaq', 'etf', 'index', 'ratio', 'trading', 'stocks'], path: '/tools/finance/spy-spx-converter', icon: '📈', isClientSide: true },
  { id: 'options-calculator', name: 'Options Profit Calculator', description: 'Calculate options profit/loss, break-even, and max gain for calls and puts', category: 'finance', keywords: ['options', 'profit', 'calculator', 'call', 'put', 'strike', 'premium', 'trading'], path: '/tools/finance/options-calculator', icon: '📊', isClientSide: true },
  { id: 'compound-interest', name: 'Compound Interest Calculator', description: 'Calculate compound interest with monthly contributions and visualize growth over time', category: 'finance', keywords: ['compound', 'interest', 'calculator', 'investment', 'growth', 'savings', 'returns'], path: '/tools/finance/compound-interest', icon: '💰', isClientSide: true },
  { id: 'stock-return', name: 'Stock Return Calculator', description: 'Calculate total return, annualized return, and CAGR for stock investments', category: 'finance', keywords: ['stock', 'return', 'calculator', 'cagr', 'annualized', 'investment', 'profit'], path: '/tools/finance/stock-return', icon: '📉', isClientSide: true },
  { id: 'pip-calculator', name: 'Forex Pip Calculator', description: 'Calculate pip value, position size, and risk for forex currency pairs', category: 'finance', keywords: ['forex', 'pip', 'calculator', 'currency', 'position', 'size', 'risk', 'trading'], path: '/tools/finance/pip-calculator', icon: '💱', isClientSide: true },
  { id: 'sip-calculator', name: 'SIP Calculator', description: 'Calculate Systematic Investment Plan returns with step-up and inflation adjustment', category: 'finance', keywords: ['sip', 'calculator', 'mutual fund', 'investment', 'monthly', 'returns', 'systematic'], path: '/tools/finance/sip-calculator', icon: '🏦', isClientSide: true },
  { id: 'tax-calculator', name: 'Income Tax Calculator', description: 'Estimate income tax liability with deductions for multiple tax regimes', category: 'finance', keywords: ['tax', 'income', 'calculator', 'deduction', 'regime', 'liability', 'estimate'], path: '/tools/finance/tax-calculator', icon: '🧾', isClientSide: true },
  { id: 'emi-calculator', name: 'EMI Calculator', description: 'Calculate Equated Monthly Installment for home, car, and personal loans with amortization table', category: 'finance', keywords: ['emi', 'calculator', 'loan', 'home', 'car', 'personal', 'installment', 'amortization'], path: '/tools/finance/emi-calculator', icon: '🏧', isClientSide: true },
  { id: 'property-calculator', name: 'Property Worth Calculator', description: 'Estimate property value based on location, size, age, and market trends with multi-currency support', category: 'finance', keywords: ['property', 'worth', 'value', 'real estate', 'house', 'estimate', 'market'], path: '/tools/finance/property-calculator', icon: '🏠', isClientSide: true },
  { id: 'rental-yield', name: 'Rental Yield Calculator', description: 'Calculate gross and net rental yield, cash-on-cash return, and monthly cash flow', category: 'finance', keywords: ['rental', 'yield', 'calculator', 'property', 'income', 'cash flow', 'landlord'], path: '/tools/finance/rental-yield', icon: '🏘️', isClientSide: true },
  { id: 'gst-calculator', name: 'GST Calculator', description: 'Calculate GST amount, inclusive and exclusive prices for different tax slabs', category: 'finance', keywords: ['gst', 'tax', 'calculator', 'inclusive', 'exclusive', 'slab', 'india', 'vat'], path: '/tools/finance/gst-calculator', icon: '🧮', isClientSide: true },
  { id: 'salary-calculator', name: 'Salary Calculator', description: 'Calculate take-home pay from CTC with tax deductions, PF, and allowances', category: 'finance', keywords: ['salary', 'calculator', 'ctc', 'take home', 'pay', 'deduction', 'pf', 'tax'], path: '/tools/finance/salary-calculator', icon: '💼', isClientSide: true },
  { id: 'retirement-calculator', name: 'Retirement Calculator', description: 'Plan retirement savings with inflation adjustment, withdrawal rate, and corpus estimation', category: 'finance', keywords: ['retirement', 'calculator', 'savings', 'corpus', 'pension', 'fire', 'withdraw'], path: '/tools/finance/retirement-calculator', icon: '🏖️', isClientSide: true },
  { id: 'fd-calculator', name: 'Fixed Deposit Calculator', description: 'Calculate maturity amount and interest earned on fixed deposits with compounding options', category: 'finance', keywords: ['fd', 'fixed deposit', 'calculator', 'maturity', 'interest', 'compounding', 'bank'], path: '/tools/finance/fd-calculator', icon: '🏛️', isClientSide: true },
  { id: 'ppf-calculator', name: 'PPF Calculator', description: 'Calculate Public Provident Fund maturity with yearly contributions over 15 years', category: 'finance', keywords: ['ppf', 'provident fund', 'calculator', 'savings', 'tax', 'government', 'india'], path: '/tools/finance/ppf-calculator', icon: '🇮🇳', isClientSide: true },
  { id: 'inflation-calculator', name: 'Inflation Calculator', description: 'Calculate the impact of inflation on purchasing power over time', category: 'finance', keywords: ['inflation', 'calculator', 'purchasing power', 'cost', 'future', 'value', 'money'], path: '/tools/finance/inflation-calculator', icon: '💸', isClientSide: true },
  { id: 'break-even-calculator', name: 'Break-Even Calculator', description: 'Calculate break-even point for business with fixed costs, variable costs, and selling price', category: 'finance', keywords: ['break even', 'calculator', 'business', 'cost', 'profit', 'revenue', 'units'], path: '/tools/finance/break-even-calculator', icon: '⚖️', isClientSide: true },
  { id: 'margin-calculator', name: 'Margin & Markup Calculator', description: 'Calculate profit margin, markup percentage, and selling price from cost', category: 'finance', keywords: ['margin', 'markup', 'calculator', 'profit', 'cost', 'selling', 'price', 'business'], path: '/tools/finance/margin-calculator', icon: '💹', isClientSide: true },
  { id: 'dividend-calculator', name: 'Dividend Yield Calculator', description: 'Calculate dividend yield, annual income, and projected growth over multiple years', category: 'finance', keywords: ['dividend', 'yield', 'calculator', 'income', 'payout', 'stock', 'annual', 'growth'], path: '/tools/finance/dividend-calculator', icon: '💵', isClientSide: true },
  { id: 'crypto-converter', name: 'Crypto Price Converter', description: 'Convert between cryptocurrencies and fiat currencies with approximate rates', category: 'finance', keywords: ['crypto', 'bitcoin', 'ethereum', 'converter', 'price', 'btc', 'eth', 'fiat', 'bnb', 'sol'], path: '/tools/finance/crypto-converter', icon: '₿', isClientSide: true },
  { id: 'currency-converter', name: 'Currency Converter', description: 'Convert between 150+ world currencies with live exchange rates', category: 'finance', keywords: ['currency', 'converter', 'exchange', 'rate', 'usd', 'eur', 'gbp', 'forex'], path: '/tools/finance/currency-converter', icon: '💱', isClientSide: true },

  // ── Encoding & Fun Tools ───────────────────────────────────────────
  { id: 'morse-code', name: 'Morse Code Translator', description: 'Convert text to Morse code and Morse code back to text with audio playback', category: 'text', keywords: ['morse', 'code', 'translator', 'dots', 'dashes', 'audio', 'sos'], path: '/tools/text/morse-code', icon: '📡', isClientSide: true },
  { id: 'braille-converter', name: 'Braille Converter', description: 'Convert text to Braille Unicode characters and back', category: 'text', keywords: ['braille', 'converter', 'accessibility', 'unicode', 'dots', 'blind'], path: '/tools/text/braille-converter', icon: '⠃', isClientSide: true },
  { id: 'binary-converter', name: 'Binary / Hex / Octal Converter', description: 'Convert between binary, hexadecimal, octal, and decimal number systems', category: 'developer', keywords: ['binary', 'hex', 'hexadecimal', 'octal', 'decimal', 'convert', 'number'], path: '/tools/developer/binary-converter', icon: '🔢', isClientSide: true },
  { id: 'ascii-art', name: 'ASCII Art Generator', description: 'Convert text to ASCII art with multiple font styles', category: 'text', keywords: ['ascii', 'art', 'text', 'font', 'banner', 'figlet', 'generator'], path: '/tools/text/ascii-art', icon: '🎭', isClientSide: true },
  { id: 'barcode-reader', name: 'Barcode Reader', description: 'Scan and decode barcodes from uploaded images using your camera or file', category: 'utility', keywords: ['barcode', 'reader', 'scan', 'decode', 'camera', 'image', 'ean', 'upc'], path: '/tools/utility/barcode-reader', icon: '📷', isClientSide: true },
  { id: 'sentiment-analysis', name: 'Sentiment Analyzer', description: 'Analyze text sentiment — positive, negative, or neutral — with confidence scores', category: 'ai', keywords: ['sentiment', 'analysis', 'positive', 'negative', 'neutral', 'emotion', 'text', 'ai'], path: '/tools/ai/sentiment-analysis', icon: '😊', isClientSide: true },
  { id: 'text-to-binary', name: 'Text to Binary', description: 'Convert text to binary representation and binary back to text', category: 'developer', keywords: ['text', 'binary', 'convert', 'encode', 'decode', 'bits'], path: '/tools/developer/text-to-binary', icon: '💾', isClientSide: true },
  { id: 'roman-numeral', name: 'Roman Numeral Converter', description: 'Convert between Roman numerals and decimal numbers', category: 'utility', keywords: ['roman', 'numeral', 'converter', 'decimal', 'number', 'MCMXCIX'], path: '/tools/utility/roman-numeral', icon: '🏛️', isClientSide: true },
  { id: 'nato-alphabet', name: 'NATO Phonetic Alphabet', description: 'Convert text to NATO phonetic alphabet (Alpha, Bravo, Charlie...)', category: 'text', keywords: ['nato', 'phonetic', 'alphabet', 'alpha', 'bravo', 'military', 'spelling'], path: '/tools/text/nato-alphabet', icon: '🎖️', isClientSide: true },
  { id: 'emoji-picker', name: 'Emoji Search & Copy', description: 'Search, browse, and copy emojis by name, category, or keyword', category: 'text', keywords: ['emoji', 'search', 'copy', 'unicode', 'emoticon', 'smiley'], path: '/tools/text/emoji-picker', icon: '😀', isClientSide: true },
  { id: 'word-frequency', name: 'Word Frequency Counter', description: 'Count word frequency and visualize the most common words in your text', category: 'text', keywords: ['word', 'frequency', 'counter', 'common', 'analysis', 'cloud'], path: '/tools/text/word-frequency', icon: '📊', isClientSide: true },
  { id: 'json-path-tester', name: 'JSONPath Tester', description: 'Test JSONPath expressions against JSON data with live results', category: 'developer', keywords: ['json', 'jsonpath', 'path', 'query', 'test', 'expression', 'filter'], path: '/tools/developer/json-path-tester', icon: '🔍', isClientSide: true },
  { id: 'markdown-table', name: 'Markdown Table Generator', description: 'Create and format Markdown tables with a visual editor', category: 'text', keywords: ['markdown', 'table', 'generator', 'format', 'visual', 'editor'], path: '/tools/text/markdown-table', icon: '📋', isClientSide: true },
  { id: 'image-metadata', name: 'Image Metadata Viewer', description: 'View and strip EXIF, IPTC, and XMP metadata from images', category: 'image', keywords: ['exif', 'metadata', 'iptc', 'xmp', 'image', 'viewer', 'strip', 'gps'], path: '/tools/image/metadata', icon: '🏷️', isClientSide: false },
  { id: 'color-blindness', name: 'Color Blindness Simulator', description: 'Simulate how images appear to people with different types of color blindness', category: 'design', keywords: ['color', 'blindness', 'simulator', 'accessibility', 'deuteranopia', 'protanopia'], path: '/tools/design/color-blindness', icon: '👁️', isClientSide: true },
  { id: 'screen-resolution', name: 'Screen Resolution Tester', description: 'Test how your website looks at different screen resolutions and devices', category: 'design', keywords: ['screen', 'resolution', 'responsive', 'device', 'viewport', 'test'], path: '/tools/design/screen-resolution', icon: '🖥️', isClientSide: true },
  { id: 'typing-speed', name: 'Typing Speed Test', description: 'Test your typing speed and accuracy with WPM and accuracy metrics', category: 'utility', keywords: ['typing', 'speed', 'test', 'wpm', 'accuracy', 'keyboard', 'practice'], path: '/tools/utility/typing-speed', icon: '⌨️', isClientSide: true },
  { id: 'random-generator', name: 'Random Data Generator', description: 'Generate random names, addresses, emails, UUIDs, credit cards, lorem ipsum, and custom schemas in JSON, CSV, SQL, or TSV', category: 'developer', keywords: ['random', 'generator', 'fake', 'data', 'name', 'email', 'address', 'test', 'faker', 'lorem', 'ipsum', 'dummy', 'mock', 'uuid', 'schema'], path: '/tools/developer/random-generator', icon: '🎲', isClientSide: true },
  { id: 'api-builder', name: 'API Request Builder', description: 'Send HTTP requests and inspect responses — a lightweight Postman alternative', category: 'developer', keywords: ['api', 'request', 'http', 'rest', 'postman', 'hoppscotch', 'fetch', 'curl', 'get', 'post'], path: '/tools/developer/api-builder', icon: '🚀', isClientSide: true },
  { id: 'crontab-guru', name: 'Crontab Guru', description: 'Build and validate cron expressions with a visual schedule builder', category: 'developer', keywords: ['cron', 'crontab', 'schedule', 'builder', 'visual', 'expression'], path: '/tools/developer/crontab-guru', icon: '📅', isClientSide: true },
  { id: 'chmod-calculator', name: 'Chmod Calculator', description: 'Calculate Unix file permissions with a visual checkbox interface', category: 'developer', keywords: ['chmod', 'permissions', 'unix', 'linux', 'file', 'calculator', 'rwx'], path: '/tools/developer/chmod-calculator', icon: '🔐', isClientSide: true },

  // ── Advanced Editors ───────────────────────────────────────────────
  { id: 'word-editor', name: 'Online Word Editor', description: 'Create and edit documents in your browser with rich formatting, tables, images, and DOCX import/export', category: 'document', keywords: ['word', 'editor', 'document', 'docx', 'doc', 'online', 'rich text', 'write', 'format', 'tables'], path: '/tools/document/word-editor', icon: '📝', isClientSide: true },
  { id: 'pdf-editor', name: 'Online PDF Editor', description: 'Edit PDFs online — add text, images, annotations, highlights, and save', category: 'document', keywords: ['pdf', 'editor', 'online', 'edit', 'text', 'image', 'annotate', 'highlight', 'save'], path: '/tools/document/pdf-editor', icon: '📝', isClientSide: false },
  { id: 'photo-editor', name: 'Online Photo Editor', description: 'Edit photos with filters, adjustments, text overlay, crop, and download', category: 'image', keywords: ['photo', 'editor', 'online', 'filter', 'adjust', 'brightness', 'contrast', 'crop', 'text'], path: '/tools/image/photo-editor', icon: '🎨', isClientSide: true },

  // ── Spreadsheet (flagship) ─────────────────────────────────────────
  { id: 'excel-editor', name: 'Online Excel Editor', description: 'Edit Excel spreadsheets in your browser with formulas, formatting, charts, and XLSX import/export', category: 'spreadsheet', keywords: ['excel', 'editor', 'spreadsheet', 'xlsx', 'xls', 'online', 'formula', 'edit', 'cells', 'sheets'], path: '/tools/spreadsheet/excel-editor', icon: '📊', isClientSide: true },
];

export default tools;