import sharp from 'sharp';
import path from 'path';
import fs from 'fs';
import archiver from 'archiver';
import { v4 as uuidv4 } from 'uuid';
import { ProcessingError } from '../utils/errors.js';
import { ensureDir, getOutputDir } from '../utils/fileHelpers.js';

/**
 * All favicon sizes to generate.
 * Each entry has a name (used for the filename) and pixel dimensions.
 */
const FAVICON_SIZES = [
  { name: 'favicon-16x16', size: 16 },
  { name: 'favicon-32x32', size: 32 },
  { name: 'favicon-48x48', size: 48 },
  { name: 'favicon-64x64', size: 64 },
  { name: 'favicon-128x128', size: 128 },
  { name: 'apple-touch-icon', size: 180 },
  { name: 'android-chrome-192x192', size: 192 },
  { name: 'android-chrome-512x512', size: 512 },
];

/**
 * Generate the HTML embedding snippet for the favicon set.
 * @returns {string}
 */
function generateHtmlSnippet() {
  return `<!-- Favicon set generated by UtilityHub -->
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="48x48" href="/favicon-48x48.png">
<link rel="icon" type="image/png" sizes="64x64" href="/favicon-64x64.png">
<link rel="icon" type="image/png" sizes="128x128" href="/favicon-128x128.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="192x192" href="/android-chrome-192x192.png">
<link rel="icon" type="image/png" sizes="512x512" href="/android-chrome-512x512.png">
`;
}

/**
 * Generate a complete favicon set from an uploaded image.
 *
 * Resizes the input image to all standard favicon sizes using 'contain' fit
 * with a transparent background, then packages everything into a ZIP archive
 * including an HTML snippet file.
 *
 * @param {string} inputPath - Absolute path to the source image
 * @returns {Promise<{ outputPath: string, outputSize: number, mimeType: string, sizes: Array<{name: string, size: number}> }>}
 */
export async function generateFavicons(inputPath) {
  if (!inputPath || !fs.existsSync(inputPath)) {
    throw new ProcessingError(
      'Input image file not found',
      'FILE_NOT_FOUND'
    );
  }

  try {
    // Validate the input is a readable image
    await sharp(inputPath).metadata();
  } catch {
    throw new ProcessingError(
      'Invalid or corrupted image file',
      'CORRUPTED_FILE'
    );
  }

  const outputDir = getOutputDir();
  await ensureDir(outputDir);

  // Create a temp directory for individual favicon files
  const tempDir = path.join(outputDir, `favicon-${uuidv4()}`);
  await ensureDir(tempDir);

  try {
    // Generate each favicon size as PNG
    const generatedFiles = [];
    for (const entry of FAVICON_SIZES) {
      const outputFilename = `${entry.name}.png`;
      const outputFilePath = path.join(tempDir, outputFilename);

      await sharp(inputPath)
        .resize(entry.size, entry.size, {
          fit: 'contain',
          background: { r: 0, g: 0, b: 0, alpha: 0 },
        })
        .png()
        .toFile(outputFilePath);

      generatedFiles.push({ name: outputFilename, path: outputFilePath, size: entry.size });
    }

    // Write the HTML snippet file
    const snippetPath = path.join(tempDir, 'favicon.html');
    fs.writeFileSync(snippetPath, generateHtmlSnippet(), 'utf-8');

    // Create ZIP archive
    const zipFilename = `favicons-${uuidv4()}.zip`;
    const zipPath = path.join(outputDir, zipFilename);

    await createZipArchive(tempDir, zipPath, generatedFiles, snippetPath);

    const zipStats = fs.statSync(zipPath);

    // Clean up temp directory
    fs.rmSync(tempDir, { recursive: true, force: true });

    return {
      outputPath: zipPath,
      outputSize: zipStats.size,
      mimeType: 'application/zip',
      sizes: FAVICON_SIZES.map((s) => ({ name: s.name, size: s.size })),
    };
  } catch (err) {
    // Clean up temp directory on error
    try {
      fs.rmSync(tempDir, { recursive: true, force: true });
    } catch {
      // ignore cleanup errors
    }

    if (err instanceof ProcessingError) throw err;
    throw new ProcessingError(
      `Favicon generation failed: ${err.message}`,
      'PROCESSING_FAILED'
    );
  }
}

/**
 * Create a ZIP archive from the generated favicon files and HTML snippet.
 *
 * @param {string} tempDir - Directory containing generated files
 * @param {string} zipPath - Output path for the ZIP file
 * @param {Array<{name: string, path: string}>} files - Generated favicon files
 * @param {string} snippetPath - Path to the HTML snippet file
 * @returns {Promise<void>}
 */
function createZipArchive(tempDir, zipPath, files, snippetPath) {
  return new Promise((resolve, reject) => {
    const output = fs.createWriteStream(zipPath);
    const archive = archiver('zip', { zlib: { level: 9 } });

    output.on('close', resolve);
    archive.on('error', (err) => reject(err));

    archive.pipe(output);

    // Add each favicon PNG
    for (const file of files) {
      archive.file(file.path, { name: file.name });
    }

    // Add the HTML snippet
    archive.file(snippetPath, { name: 'favicon.html' });

    archive.finalize();
  });
}

export { FAVICON_SIZES };
export default { generateFavicons, FAVICON_SIZES };
